export const columns = [
  { name: "NAME", uid: "name" },
  { name: "ROLE", uid: "role" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];

export const users = [
  {
    id: 1,
    name: "Lionel Messi",
    role: "Yard Supervisor",
    team: "Operations",
    status: "active",
    age: "35",
    avatar: "https://i.pravatar.cc/150?u=a0123456789",
    email: "lionel.messi@example.com",
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    role: "Logistics Coordinator",
    team: "Logistics",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a9876543210",
    email: "cristiano.ronaldo@example.com",
  },
  {
    id: 3,
    name: "Neymar Jr",
    role: "Warehouse Manager",
    team: "Warehouse",
    status: "active",
    age: "42",
    avatar: "https://i.pravatar.cc/150?u=a5432167890",
    email: "neymar.jr@example.com",
  },
  {
    id: 4,
    name: "Luis Suárez",
    role: "Forklift Operator",
    team: "Operations",
    status: "on break",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a0987654321",
    email: "luis.suarez@example.com",
  },
  {
    id: 5,
    name: "Gareth Bale",
    role: "Inventory Specialist",
    team: "Inventory",
    status: "active",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a1357924680",
    email: "gareth.bale@example.com",
  },
  {
    id: 6,
    name: "Paul Pogba",
    role: "Yard Assistant",
    team: "Operations",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a2468135790",
    email: "paul.pogba@example.com",
  },
  {
    id: 7,
    name: "Manuel Neuer",
    role: "Safety Officer",
    team: "Safety",
    status: "inactive",
    age: "38",
    avatar: "https://i.pravatar.cc/150?u=a9876543210",
    email: "manuel.neuer@example.com",
  },
  {
    id: 8,
    name: "Robert Lewandowski",
    role: "Maintenance Crew",
    team: "Maintenance",
    status: "on break",
    age: "33",
    avatar: "https://i.pravatar.cc/150?u=a0123456789",
    email: "robert.lewandowski@example.com",
  },
  {
    id: 9,
    name: "Sergio Agüero",
    role: "Transport Planner",
    team: "Logistics",
    status: "active",
    age: "40",
    avatar: "https://i.pravatar.cc/150?u=a0987654321",
    email: "sergio.aguero@example.com",
  },
  {
    id: 10,
    name: "James Rodríguez",
    role: "Quality Control",
    team: "Quality",
    status: "inactive",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a5432167890",
    email: "james.rodriguez@example.com",
  },
  {
    id: 11,
    name: "Thiago Silva",
    role: "Operations Manager",
    team: "Operations",
    status: "active",
    age: "36",
    avatar: "https://i.pravatar.cc/150?u=a1357924680",
    email: "thiago.silva@example.com",
  },
  {
    id: 12,
    name: "David Silva",
    role: "Data Analyst",
    team: "Data",
    status: "active",
    age: "30",
    avatar: "https://i.pravatar.cc/150?u=a2468135790",
    email: "david.silva@example.com",
  },
  {
    id: 13,
    name: "Zlatan Ibrahimović",
    role: "Fleet Manager",
    team: "Fleet",
    status: "active",
    age: "44",
    avatar: "https://i.pravatar.cc/150?u=a0987654321",
    email: "zlatan.ibrahimovic@example.com",
  },
  {
    id: 14,
    name: "Arjen Robben",
    role: "Administrative Assistant",
    team: "Administration",
    status: "on break",
    age: "26",
    avatar: "https://i.pravatar.cc/150?u=a5432167890",
    email: "arjen.robben@example.com",
  },
  {
    id: 15,
    name: "Franck Ribéry",
    role: "Yard Supervisor",
    team: "Operations",
    status: "active",
    age: "34",
    avatar: "https://i.pravatar.cc/150?u=a1357924680",
    email: "franck.ribery@example.com",
  },
  {
    id: 16,
    name: "Andrés Iniesta",
    role: "Inventory Clerk",
    team: "Inventory",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a2468135790",
    email: "andres.iniesta@example.com",
  },
];
